### ISSUE TITLE
Error opening the Keyboard

### ISSUE THREAD

**Issue by talesam** [fredcw/Cinnamenu#3]
I found this error very strange, Cinnamenu does not create any files in the indicated location, but when I try to open the keyboard in Cinnamon, I get this error, trying to look for a json matedata file there.

```
cinnamon-settings keyboard
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:460: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Keyboard module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 813, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 332, in __init__
    if self.load_sidepage_as_standalone():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 466, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 187, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py", line 538, in on_module_selected
    with open(f"{home}/.local/share/cinnamon/{_type}/{name}/metadata.json", encoding="utf-8") as metadata:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/home/tales/.local/share/cinnamon/applets/Cinnamenu@json/metadata.json'

```

**Comment by fredcw** [comment]
Yes, this is due to a bug in cinnamon-settings keyboard module. It's now been fixed (https://shorturl.at/hqvP0) but the fix won't appear until the next version of cinnamon (mint 22.1). 

The way to fix this is to install (download) and then uninstall (delete) cinnamenu applet using the cinnamon settings applets dialog. You may also have to add it to a panel and then remove it again as well, I'm not sure.

The shortcut key to open the menu will then be unregistered and then cinnamon-settings keyboard will not try to find it again.

**Comment by fredcw** [comment]
@gbit00
